[package]
name = "tensor-automaker"
version = "0.1.0"
edition = "2021"

[dependencies]

# Serde
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
serde_json = "1.0.108"

# Tokio / Futures
futures = "0.3.30"
tokio = { version = "1.35.1", default-features = false, features = [
    "macros",
    "sync",
    "rt-multi-thread",
] }
tokio-stream = { version = "0.1.14", default-features = false, features = [
    "sync",
] }

# GraphQL
graphql_client = { version = "0.13.0", default-features = false, features = [
    "graphql_query_derive",
] }

# HTTP / Websocket
tokio-tungstenite = { version = "0.21.0", default-features = false, features = [
    "rustls",
    "connect",
    "native-tls",
] }

# External
url = "2.5.0"
uuid = { version = "1.6.1", default-features = false, features = [
    "v4",
    "serde",
] }
anyhow = "1.0.77"
